version: '3.5'
name: feed

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile_backend
    # command: sh -c "sh ./entry_backend.sh"
    # command: sh -c "tail -f /dev/null" 

    container_name: feed_backend
    ports:
      - 8000:8000
    # env_file:
    #   - ../backend/.env.sample
    volumes:
      - ./db/:/app/db
  nginx:
    build:
      context: ./nginx
    command: sh -c "nginx"
    # command: sh -c "tail -f /dev/null" 
    container_name: feed_nginx
    ports:
      - 81:80
  # admin:
  #   build:
  #     context: ../
  #     dockerfile: ./local-dev/Dockerfile_front
  #   command: sh -c "cd ./packages/admin && yarn dev"
  #   container_name: feed_admin
  #   ports:
  #     - 3002:3002
  #   volumes:
  #     - ../packages/admin/:/app/packages/admin
  # scanner:
  #   build:
  #     context: ../
  #     dockerfile: ./local-dev/Dockerfile_front
  #   command: sh -c "cd ./packages/scanner && yarn dev"
  #   container_name: feed_scanner
  #   ports:
  #     - 3001:3001
  #   volumes:
  #     - ../packages/scanner/:/app/packages/scanner
