version: '3.5'

x-defaults: &defaults
  env_file:
    - ./.env
  volumes:
    - ./shared/:/shared
    - ../db/:/db
    - ./:/app

services:
  backend:
    build:
      dockerfile: Dockerfile
    command: bash -c "python manage.py migrate &&
        python /app/cron_config.py &&
        cron &&
        gunicorn config.wsgi:application --bind 0.0.0.0:8000"
    container_name: feed_backend
    ports:
      - 8000:8000
    <<: *defaults
