name: Deploy to fest

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: [self-hosted, feedsrv]
    env:
      IMAGE_NAME_BASENAME: feed-admin
      DB_DIR: /var/feed_db
    steps:
    - uses: actions/checkout@v3
# DB
    - name: setup db dir
      run: mkdir -p ${DB_DIR}
# ADMIN
    - name: build admin
      run: |
          docker build \
             --progress=plain \
             -t $IMAGE_NAME_BASENAME:$GITHUB_SHA  \
             --build-arg NEW_API_URL=https://feedapp.insomniafest.ru/feedapi/v1 \
             --build-arg SYNC_URL=http://prod.agreetesting.rumyantsev.com/api/v1/feeder/ \
             --build-arg SYNC_LOGIN=${{ secrets.SYNC_LOGIN }} \
             --build-arg SYNC_PASSWORD=${{ secrets.SYNC_PASSWORD }} \
             --build-arg ENABLE_SYNC_TO_NOTION=True \
            .
    - name: stop admin
      run: docker rm -f $IMAGE_NAME_BASENAME
    - name: run admin
      run: |
        docker run -d \
          -p 4262:4262 -p 4301:4301 -p 8888:80 \
          -v ${DB_DIR}:/app/db \
          --restart=always \
          --name $IMAGE_NAME_BASENAME \
          $IMAGE_NAME_BASENAME:$GITHUB_SHA
# CLEANUP
    # - name: cleanup docker containers
    #   run: docker container prune --filter "until=168h" -f
    # - name: cleanup docker images
    #   run: docker image prune -a -f --filter "until=168h"
    # - name: cleanup docker build cache
    #   run: docker builder prune -a -f --filter "until=168h"
