name: Tests
# on: [workflow_dispatch]
on: [push]
# on:
#   workflow_dispatch:

jobs:
  try_gitlab_cicd:
    runs-on: ubuntu-latest

    container:
      image: ubuntu:latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Docker plus Compose
        run: |
          apt-get update
          apt-get install -y docker-compose-v2

      - name: Check Docker
        run: |
          docker compose version
          docker version
          docker info
        continue-on-error: true

      - name: 🍏 Try some testing
        run: |
          cd tests
          bash run_tests.sh || touch /tmp/testFailed

      - name: "Shorter test log"
        run: cat /tmp/tests.short.log

      - name: "Verdict"
        run: if [ -f /tmp/testFailed ]; then
          echo "Tests Failed"; exit 1;
          else
          echo "Tests Success";
          fi

